/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceBodyDeclaration.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.orbisgis.core.javaManager.parser;

public class ASTClassOrInterfaceBodyDeclaration extends SimpleNode {
  public ASTClassOrInterfaceBodyDeclaration(int id) {
    super(id);
  }

  public ASTClassOrInterfaceBodyDeclaration(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d10281dd669bfef2eb7098c78f6cf543 (do not edit this line) */
