/* Generated By:JJTree: Do not edit this line. ASTMarkerAnnotation.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.orbisgis.core.javaManager.parser;

public class ASTMarkerAnnotation extends SimpleNode {
  public ASTMarkerAnnotation(int id) {
    super(id);
  }

  public ASTMarkerAnnotation(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1375ce33d818b876e91bdc0cea4934e2 (do not edit this line) */
