//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.02 at 10:59:16 AM CEST 
//


package net.opengis.se._2_0.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExternalGraphicType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExternalGraphicType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/se/2.0/core}GraphicType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="OnlineResource" type="{http://www.opengis.net/se/2.0/core}VariableOnlineResourceType"/>
 *           &lt;element ref="{http://www.opengis.net/se/2.0/core}InlineContent"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.opengis.net/se/2.0/core}Format"/>
 *         &lt;element ref="{http://www.opengis.net/se/2.0/core}ViewBox" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/se/2.0/core}Transform" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/se/2.0/core}Opacity" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/se/2.0/core}Halo" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="uom" type="{http://www.opengis.net/se/2.0/core}UomType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExternalGraphicType", propOrder = {
    "onlineResource",
    "inlineContent",
    "format",
    "viewBox",
    "transform",
    "opacity",
    "halo"
})
public class ExternalGraphicType
    extends GraphicType
{

    @XmlElement(name = "OnlineResource")
    protected VariableOnlineResourceType onlineResource;
    @XmlElement(name = "InlineContent")
    protected InlineContentType inlineContent;
    @XmlElement(name = "Format", required = true)
    protected String format;
    @XmlElement(name = "ViewBox")
    protected ViewBoxType viewBox;
    @XmlElement(name = "Transform")
    protected TransformType transform;
    @XmlElement(name = "Opacity")
    protected ParameterValueType opacity;
    @XmlElement(name = "Halo")
    protected HaloType halo;
    @XmlAttribute
    protected String uom;

    /**
     * Gets the value of the onlineResource property.
     * 
     * @return
     *     possible object is
     *     {@link VariableOnlineResourceType }
     *     
     */
    public VariableOnlineResourceType getOnlineResource() {
        return onlineResource;
    }

    /**
     * Sets the value of the onlineResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableOnlineResourceType }
     *     
     */
    public void setOnlineResource(VariableOnlineResourceType value) {
        this.onlineResource = value;
    }

    /**
     * Gets the value of the inlineContent property.
     * 
     * @return
     *     possible object is
     *     {@link InlineContentType }
     *     
     */
    public InlineContentType getInlineContent() {
        return inlineContent;
    }

    /**
     * Sets the value of the inlineContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link InlineContentType }
     *     
     */
    public void setInlineContent(InlineContentType value) {
        this.inlineContent = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the viewBox property.
     * 
     * @return
     *     possible object is
     *     {@link ViewBoxType }
     *     
     */
    public ViewBoxType getViewBox() {
        return viewBox;
    }

    /**
     * Sets the value of the viewBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewBoxType }
     *     
     */
    public void setViewBox(ViewBoxType value) {
        this.viewBox = value;
    }

    /**
     * Gets the value of the transform property.
     * 
     * @return
     *     possible object is
     *     {@link TransformType }
     *     
     */
    public TransformType getTransform() {
        return transform;
    }

    /**
     * Sets the value of the transform property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransformType }
     *     
     */
    public void setTransform(TransformType value) {
        this.transform = value;
    }

    /**
     * Gets the value of the opacity property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterValueType }
     *     
     */
    public ParameterValueType getOpacity() {
        return opacity;
    }

    /**
     * Sets the value of the opacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterValueType }
     *     
     */
    public void setOpacity(ParameterValueType value) {
        this.opacity = value;
    }

    /**
     * Gets the value of the halo property.
     * 
     * @return
     *     possible object is
     *     {@link HaloType }
     *     
     */
    public HaloType getHalo() {
        return halo;
    }

    /**
     * Sets the value of the halo property.
     * 
     * @param value
     *     allowed object is
     *     {@link HaloType }
     *     
     */
    public void setHalo(HaloType value) {
        this.halo = value;
    }

    /**
     * Gets the value of the uom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUom() {
        return uom;
    }

    /**
     * Sets the value of the uom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUom(String value) {
        this.uom = value;
    }

}
