/* Generated By:JJTree: Do not edit this line. ASTSQLOrderBy.java */

package org.gdms.sql.parser;

public class ASTSQLOrderBy extends SimpleNode {
  public ASTSQLOrderBy(int id) {
    super(id);
  }

  public ASTSQLOrderBy(SQLEngine p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLEngineVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
