/* Generated By:JJTree: Do not edit this line. ASTSQLSelectAllCols.java */

package org.gdms.sql.parser;

public class ASTSQLSelectAllCols extends SimpleNode {
  public ASTSQLSelectAllCols(int id) {
    super(id);
  }

  public ASTSQLSelectAllCols(SQLEngine p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLEngineVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
