/* Generated By:JJTree: Do not edit this line. ASTSQLSelectAllColsInTable.java */

package org.gdms.sql.parser;

public class ASTSQLSelectAllColsInTable extends SimpleNode {
  public ASTSQLSelectAllColsInTable(int id) {
    super(id);
  }

  public ASTSQLSelectAllColsInTable(SQLEngine p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLEngineVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
