/* Generated By:JJTree: Do not edit this line. ASTSQLTypeArgs.java */

package org.gdms.sql.parser;

public class ASTSQLTypeArgs extends SimpleNode {
  public ASTSQLTypeArgs(int id) {
    super(id);
  }

  public ASTSQLTypeArgs(SQLEngine p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLEngineVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
