/* Generated By:JJTree: Do not edit this line. ASTSQLColumnDefinition.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.gdms.sql.parser;

public
class ASTSQLColumnDefinition extends SimpleNode {
  public ASTSQLColumnDefinition(int id) {
    super(id);
  }

  public ASTSQLColumnDefinition(SQLEngine p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLEngineVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=69dfc71d6becbc19dd9a3343e1cc6471 (do not edit this line) */
