/* Generated By:JJTree: Do not edit this line. ASTSQLAddColumn.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.gdms.sql.parser;

public
class ASTSQLAddColumn extends SimpleNode {
  public ASTSQLAddColumn(int id) {
    super(id);
  }

  public ASTSQLAddColumn(SQLEngine p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLEngineVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dc2fefd5df9695537974eca2ea7de635 (do not edit this line) */
