/* Generated By:JJTree: Do not edit this line. ASTSQLCreateArgsList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.gdms.sql.parser;

public
class ASTSQLCreateArgsList extends SimpleNode {
  public ASTSQLCreateArgsList(int id) {
    super(id);
  }

  public ASTSQLCreateArgsList(SQLEngine p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLEngineVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6c7d09504c96d834733628be3b67ab54 (do not edit this line) */
