/*
 * OrbisGIS is a GIS application dedicated to scientific spatial simulation.
 * This cross-platform GIS is developed at French IRSTV institute and is able
 * to manipulate and create vector and raster spatial information. OrbisGIS
 * is distributed under GPL 3 license. It is produced  by the geo-informatic team of
 * the IRSTV Institute <http://www.irstv.cnrs.fr/>, CNRS FR 2488:
 *    Erwan BOCHER, scientific researcher,
 *    Thomas LEDUC, scientific researcher,
 *    Fernando GONZALEZ CORTES, computer engineer.
 *
 * Copyright (C) 2007 Erwan BOCHER, Fernando GONZALEZ CORTES, Thomas LEDUC
 *
 * This file is part of OrbisGIS.
 *
 * OrbisGIS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OrbisGIS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OrbisGIS. If not, see <http://www.gnu.org/licenses/>.
 *
 * For more information, please consult:
 *    <http://orbisgis.cerma.archi.fr/>
 *    <http://sourcesup.cru.fr/projects/orbisgis/>
 *
 * or contact directly:
 *    erwan.bocher _at_ ec-nantes.fr
 *    fergonco _at_ gmail.com
 *    thomas.leduc _at_ cerma.archi.fr
 */
/* Generated By:JJTree: Do not edit this line. ../src/main/java/org/gdms/sql/parser/SQLEngineTreeConstants.java */

package org.gdms.sql.parser;

public interface SQLEngineTreeConstants
{
  public int JJTSQLANDEXPR = 0;
  public int JJTSQLBETWEENCLAUSE = 1;
  public int JJTSQLCOLREF = 2;
  public int JJTSQLCOMPAREEXPR = 3;
  public int JJTSQLCOMPAREEXPRRIGHT = 4;
  public int JJTSQLCOMPAREOP = 5;
  public int JJTSQLDELETE = 6;
  public int JJTSQLDROP = 7;
  public int JJTSQLEXISTSCLAUSE = 8;
  public int JJTSQLFUNCTION = 9;
  public int JJTSQLFUNCTIONARGS = 10;
  public int JJTSQLGROUPBY = 11;
  public int JJTSQLGROUPBYLIST = 12;
  public int JJTSQLID = 13;
  public int JJTSQLINCLAUSE = 14;
  public int JJTSQLINSERT = 15;
  public int JJTSQLISCLAUSE = 16;
  public int JJTSQLLEFTJOINCLAUSE = 17;
  public int JJTSQLLIKECLAUSE = 18;
  public int JJTSQLLITERAL = 19;
  public int JJTSQLNOTEXPR = 20;
  public int JJTSQLORDERBY = 21;
  public int JJTSQLORDERBYELEM = 22;
  public int JJTSQLORDERBYLIST = 23;
  public int JJTSQLORDERDIRECTION = 24;
  public int JJTSQLOREXPR = 25;
  public int JJTSQLPATTERN = 26;
  public int JJTSQLPRODUCTEXPR = 27;
  public int JJTSQLPRODUCTSYMBOL = 28;
  public int JJTSQLRIGHTJOINCLAUSE = 29;
  public int JJTSQLSCRIPT = 30;
  public int JJTSQLSELECT = 31;
  public int JJTSQLSELECTALLCOLS = 32;
  public int JJTSQLSELECTALLCOLSINTABLE = 33;
  public int JJTSQLSELECTCOLS = 34;
  public int JJTSQLSELECTLIMIT = 35;
  public int JJTSQLSELECTLIST = 36;
  public int JJTSQLSELECTOFFSET = 37;
  public int JJTSQLSTATEMENT = 38;
  public int JJTSQLSUMEXPR = 39;
  public int JJTSQLSUMSYMBOL = 40;
  public int JJTSQLTABLELIST = 41;
  public int JJTSQLTABLEREF = 42;
  public int JJTSQLTERM = 43;
  public int JJTSQLUNARYEXPR = 44;
  public int JJTSQLUNION = 45;
  public int JJTSQLUPDATE = 46;
  public int JJTSQLUPDATEASSIGNMENT = 47;
  public int JJTSQLLVALUEELEMENT = 48;
  public int JJTSQLVALUELIST = 49;
  public int JJTSQLWHERE = 50;
  public int JJTSQLCREATE = 51;
  public int JJTSQLCREATEARGSLIST = 52;
  public int JJTSQLCOLUMNDEFINITION = 53;
  public int JJTSQLDATATYPECONSTRAINT = 54;
  public int JJTSQLTYPEARGLITERAL = 55;
  public int JJTSQLTYPEARGS = 56;


  public String[] jjtNodeName = {
    "SQLAndExpr",
    "SQLBetweenClause",
    "SQLColRef",
    "SQLCompareExpr",
    "SQLCompareExprRight",
    "SQLCompareOp",
    "SQLDelete",
    "SQLDrop",
    "SQLExistsClause",
    "SQLFunction",
    "SQLFunctionArgs",
    "SQLGroupBy",
    "SQLGroupByList",
    "SQLId",
    "SQLInClause",
    "SQLInsert",
    "SQLIsClause",
    "SQLLeftJoinClause",
    "SQLLikeClause",
    "SQLLiteral",
    "SQLNotExpr",
    "SQLOrderBy",
    "SQLOrderByElem",
    "SQLOrderByList",
    "SQLOrderDirection",
    "SQLOrExpr",
    "SQLPattern",
    "SQLProductExpr",
    "SQLProductSymbol",
    "SQLRightJoinClause",
    "SQLScript",
    "SQLSelect",
    "SQLSelectAllCols",
    "SQLSelectAllColsInTable",
    "SQLSelectCols",
    "SQLSelectLimit",
    "SQLSelectList",
    "SQLSelectOffset",
    "SQLStatement",
    "SQLSumExpr",
    "SQLSumSymbol",
    "SQLTableList",
    "SQLTableRef",
    "SQLTerm",
    "SQLUnaryExpr",
    "SQLUnion",
    "SQLUpdate",
    "SQLUpdateAssignment",
    "SQLLValueElement",
    "SQLValueList",
    "SQLWhere",
    "SQLCreate",
    "SQLCreateArgsList",
    "SQLColumnDefinition",
    "SQLDataTypeConstraint",
    "SQLTypeArgLiteral",
    "SQLTypeArgs",
  };
}
