package org.gdms.sql.parser;
/* Generated By:JJTree&JavaCC: Do not edit this line. SQLEngineConstants.java */
public interface SQLEngineConstants {

  int EOF = 0;
  int COMMENT_LINE = 5;
  int COMMENT_BLOCK = 6;
  int ALL = 7;
  int AND = 8;
  int AS = 9;
  int ASC = 10;
  int BEGIN = 11;
  int BETWEEN = 12;
  int BY = 13;
  int CUSTOM = 14;
  int DESC = 15;
  int DISTINCT = 16;
  int FROM = 17;
  int GROUP = 18;
  int HAVING = 19;
  int IN = 20;
  int IS = 21;
  int LIKE = 22;
  int NOT = 23;
  int NULL = 24;
  int OR = 25;
  int ORDER = 26;
  int SELECT = 27;
  int UNION = 28;
  int SPACES = 29;
  int TABLES = 30;
  int WHERE = 31;
  int DELETE = 32;
  int EXISTS = 33;
  int INSERT = 34;
  int INTO = 35;
  int SET = 36;
  int UPDATE = 37;
  int VALUES = 38;
  int INTEGER_LITERAL = 39;
  int FLOATING_POINT_LITERAL = 40;
  int EXPONENT = 41;
  int STRING_LITERAL = 42;
  int ID = 43;
  int LETTER = 44;
  int DIGIT = 45;
  int ASSIGN = 46;
  int CONCAT = 47;
  int SEMICOLON = 48;
  int DOT = 49;
  int TILDE = 50;
  int LESS = 51;
  int LESSEQUAL = 52;
  int GREATER = 53;
  int GREATEREQUAL = 54;
  int EQUAL = 55;
  int NOTEQUAL = 56;
  int NOTEQUAL2 = 57;
  int JOINPLUS = 58;
  int OPENPAREN = 59;
  int CLOSEPAREN = 60;
  int ASTERISK = 61;
  int SLASH = 62;
  int PLUS = 63;
  int MINUS = 64;
  int QUESTIONMARK = 65;
  int COMPARISON = 66;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<COMMENT_LINE>",
    "<COMMENT_BLOCK>",
    "\"all\"",
    "\"and\"",
    "\"as\"",
    "\"asc\"",
    "\"begin\"",
    "\"between\"",
    "\"by\"",
    "\"custom\"",
    "\"desc\"",
    "\"distinct\"",
    "\"from\"",
    "\"group\"",
    "\"having\"",
    "\"in\"",
    "\"is\"",
    "\"like\"",
    "\"not\"",
    "\"null\"",
    "\"or\"",
    "\"order\"",
    "\"select\"",
    "\"union\"",
    "\"spaces\"",
    "\"tables\"",
    "\"where\"",
    "\"delete\"",
    "\"exists\"",
    "\"insert\"",
    "\"into\"",
    "\"set\"",
    "\"update\"",
    "\"values\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\":=\"",
    "\"||\"",
    "\";\"",
    "\".\"",
    "\"~\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\"!=\"",
    "\"<>\"",
    "\"(+)\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"?\"",
    "<COMPARISON>",
    "\",\"",
  };

}
