/* Generated By:JJTree: Do not edit this line. ../../src/main/java/com/hardcode/gdbms/parser/SQLEngineTreeConstants.java */

package org.gdms.sql.parser;

public interface SQLEngineTreeConstants {
	public int JJTSQLANDEXPR = 0;

	public int JJTSQLBETWEENCLAUSE = 1;

	public int JJTSQLCOLREF = 2;

	public int JJTSQLCOMPAREEXPR = 3;

	public int JJTSQLCOMPAREEXPRRIGHT = 4;

	public int JJTSQLCOMPAREOP = 5;

	public int JJTSQLCUSTOM = 6;

	public int JJTSQLDELETE = 7;

	public int JJTSQLEXISTSCLAUSE = 8;

	public int JJTSQLFUNCTION = 9;

	public int JJTSQLFUNCTIONARGS = 10;

	public int JJTSQLGROUPBY = 11;

	public int JJTSQLINCLAUSE = 12;

	public int JJTSQLINSERT = 13;

	public int JJTSQLISCLAUSE = 14;

	public int JJTSQLLEFTJOINCLAUSE = 15;

	public int JJTSQLLIKECLAUSE = 16;

	public int JJTSQLLITERAL = 17;

	public int JJTSQLLVALUE = 18;

	public int JJTSQLLVALUETERM = 19;

	public int JJTSQLNOTEXPR = 20;

	public int JJTSQLORDERBY = 21;

	public int JJTSQLORDERBYELEM = 22;

	public int JJTSQLORDERBYLIST = 23;

	public int JJTSQLORDERDIRECTION = 24;

	public int JJTSQLOREXPR = 25;

	public int JJTSQLPATTERN = 26;

	public int JJTSQLPRODUCTEXPR = 27;

	public int JJTSQLRIGHTJOINCLAUSE = 28;

	public int JJTSQLUNION = 29;

	public int JJTSQLSELECT = 30;

	public int JJTSQLSELECTCOLS = 31;

	public int JJTSQLSELECTLIST = 32;

	public int JJTSQLSTATEMENT = 33;

	public int JJTSQLSUMEXPR = 34;

	public int JJTSQLTABLELIST = 35;

	public int JJTSQLTABLEREF = 36;

	public int JJTSQLTERM = 37;

	public int JJTSQLUNARYEXPR = 38;

	public int JJTSQLUPDATE = 39;

	public int JJTSQLUPDATEASSIGNMENT = 40;

	public int JJTSQLLVALUEELEMENT = 41;

	public int JJTSQLLVALUELIST = 42;

	public int JJTSQLWHERE = 43;

	public String[] jjtNodeName = { "SQLAndExpr", "SQLBetweenClause",
			"SQLColRef", "SQLCompareExpr", "SQLCompareExprRight",
			"SQLCompareOp", "SQLCustom", "SQLDelete", "SQLExistsClause",
			"SQLFunction", "SQLFunctionArgs", "SQLGroupBy", "SQLInClause",
			"SQLInsert", "SQLIsClause", "SQLLeftJoinClause", "SQLLikeClause",
			"SQLLiteral", "SQLLvalue", "SQLLvalueTerm", "SQLNotExpr",
			"SQLOrderBy", "SQLOrderByElem", "SQLOrderByList",
			"SQLOrderDirection", "SQLOrExpr", "SQLPattern", "SQLProductExpr",
			"SQLRightJoinClause", "SQLUnion", "SQLSelect", "SQLSelectCols",
			"SQLSelectList", "SQLStatement", "SQLSumExpr", "SQLTableList",
			"SQLTableRef", "SQLTerm", "SQLUnaryExpr", "SQLUpdate",
			"SQLUpdateAssignment", "SQLLValueElement", "SQLLValueList",
			"SQLWhere", };
}
