/*
 * The GDMS library (Generic Datasources Management System)
 * is a middleware dedicated to the management of various kinds of
 * data-sources such as spatial vectorial data or alphanumeric. Based
 * on the JTS library and conform to the OGC simple feature access
 * specifications, it provides a complete and robust API to manipulate
 * in a SQL way remote DBMS (PostgreSQL, H2...) or flat files (.shp,
 * .csv...). GDMS is produced  by the geomatic team of the IRSTV
 * Institute <http://www.irstv.cnrs.fr/>, CNRS FR 2488:
 *    Erwan BOCHER, scientific researcher,
 *    Thomas LEDUC, scientific researcher,
 *    Fernando GONZALES CORTES, computer engineer.
 *
 * Copyright (C) 2007 Erwan BOCHER, Fernando GONZALES CORTES, Thomas LEDUC
 *
 * This file is part of GDMS.
 *
 * GDMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GDMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GDMS. If not, see <http://www.gnu.org/licenses/>.
 *
 * For more information, please consult:
 *    <http://orbisgis.cerma.archi.fr/>
 *    <http://sourcesup.cru.fr/projects/orbisgis/>
 *    <http://listes.cru.fr/sympa/info/orbisgis-developers/>
 *    <http://listes.cru.fr/sympa/info/orbisgis-users/>
 *
 * or contact directly:
 *    erwan.bocher _at_ ec-nantes.fr
 *    fergonco _at_ gmail.com
 *    thomas.leduc _at_ cerma.archi.fr
 */
/* Generated By:JJTree: Do not edit this line. ../src/main/java/org/gdms/sql/parser/SQLEngineVisitor.java */

package org.gdms.sql.parser;

public interface SQLEngineVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTSQLAndExpr node, Object data);
  public Object visit(ASTSQLBetweenClause node, Object data);
  public Object visit(ASTSQLColRef node, Object data);
  public Object visit(ASTSQLCompareExpr node, Object data);
  public Object visit(ASTSQLCompareExprRight node, Object data);
  public Object visit(ASTSQLCompareOp node, Object data);
  public Object visit(ASTSQLDelete node, Object data);
  public Object visit(ASTSQLExistsClause node, Object data);
  public Object visit(ASTSQLFunction node, Object data);
  public Object visit(ASTSQLFunctionArgs node, Object data);
  public Object visit(ASTSQLGroupBy node, Object data);
  public Object visit(ASTSQLInClause node, Object data);
  public Object visit(ASTSQLInsert node, Object data);
  public Object visit(ASTSQLIsClause node, Object data);
  public Object visit(ASTSQLLeftJoinClause node, Object data);
  public Object visit(ASTSQLLikeClause node, Object data);
  public Object visit(ASTSQLLiteral node, Object data);
  public Object visit(ASTSQLLvalue node, Object data);
  public Object visit(ASTSQLLvalueTerm node, Object data);
  public Object visit(ASTSQLNotExpr node, Object data);
  public Object visit(ASTSQLOrderBy node, Object data);
  public Object visit(ASTSQLOrderByElem node, Object data);
  public Object visit(ASTSQLOrderByList node, Object data);
  public Object visit(ASTSQLOrderDirection node, Object data);
  public Object visit(ASTSQLOrExpr node, Object data);
  public Object visit(ASTSQLPattern node, Object data);
  public Object visit(ASTSQLProductExpr node, Object data);
  public Object visit(ASTSQLRightJoinClause node, Object data);
  public Object visit(ASTSQLUnion node, Object data);
  public Object visit(ASTSQLSelect node, Object data);
  public Object visit(ASTSQLSelectCols node, Object data);
  public Object visit(ASTSQLSelectList node, Object data);
  public Object visit(ASTSQLStatement node, Object data);
  public Object visit(ASTSQLSumExpr node, Object data);
  public Object visit(ASTSQLTableList node, Object data);
  public Object visit(ASTSQLTableRef node, Object data);
  public Object visit(ASTSQLTerm node, Object data);
  public Object visit(ASTSQLUnaryExpr node, Object data);
  public Object visit(ASTSQLUpdate node, Object data);
  public Object visit(ASTSQLUpdateAssignment node, Object data);
  public Object visit(ASTSQLLValueElement node, Object data);
  public Object visit(ASTSQLLValueList node, Object data);
  public Object visit(ASTSQLWhere node, Object data);
  public Object visit(ASTSQLCreate node, Object data);
  public Object visit(ASTSQLCreateArgsList node, Object data);
  public Object visit(ASTSQLColumnDefinition node, Object data);
  public Object visit(ASTSQLDataTypeConstraint node, Object data);
  public Object visit(ASTSQLTypeArgLiteral node, Object data);
  public Object visit(ASTSQLTypeArgs node, Object data);
}
