//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.14 at 03:50:38 PM CEST 
//


package org.orbisgis.core.renderer.symbol.collection.persistence;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.orbisgis.core.renderer.symbol.collection.persistence package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SymbolComposite_QNAME = new QName("org.orbisgis.symbol", "symbol-composite");
    private final static QName _SimpleSymbol_QNAME = new QName("org.orbisgis.symbol", "simple-symbol");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.orbisgis.core.renderer.symbol.collection.persistence
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SimpleSymbolType }
     * 
     */
    public SimpleSymbolType createSimpleSymbolType() {
        return new SimpleSymbolType();
    }

    /**
     * Create an instance of {@link SymbolList }
     * 
     */
    public SymbolList createSymbolList() {
        return new SymbolList();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link SymbolCompositeType }
     * 
     */
    public SymbolCompositeType createSymbolCompositeType() {
        return new SymbolCompositeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SymbolCompositeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "org.orbisgis.symbol", name = "symbol-composite")
    public JAXBElement<SymbolCompositeType> createSymbolComposite(SymbolCompositeType value) {
        return new JAXBElement<SymbolCompositeType>(_SymbolComposite_QNAME, SymbolCompositeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleSymbolType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "org.orbisgis.symbol", name = "simple-symbol")
    public JAXBElement<SimpleSymbolType> createSimpleSymbol(SimpleSymbolType value) {
        return new JAXBElement<SimpleSymbolType>(_SimpleSymbol_QNAME, SimpleSymbolType.class, null, value);
    }

}
