//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.22 at 02:44:27 PM CEST 
//


package org.orbisgis.core.layerModel.persistence;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.orbisgis.core.layerModel.persistence package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LayerCollection_QNAME = new QName("org.orbisgis.mapContext", "layer-collection");
    private final static QName _Layer_QNAME = new QName("org.orbisgis.mapContext", "layer");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.orbisgis.core.layerModel.persistence
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SelectedLayer }
     * 
     */
    public SelectedLayer createSelectedLayer() {
        return new SelectedLayer();
    }

    /**
     * Create an instance of {@link BoundingBox }
     * 
     */
    public BoundingBox createBoundingBox() {
        return new BoundingBox();
    }

    /**
     * Create an instance of {@link MapContext }
     * 
     */
    public MapContext createMapContext() {
        return new MapContext();
    }

    /**
     * Create an instance of {@link LayerType }
     * 
     */
    public LayerType createLayerType() {
        return new LayerType();
    }

    /**
     * Create an instance of {@link OgcCrs }
     * 
     */
    public OgcCrs createOgcCrs() {
        return new OgcCrs();
    }

    /**
     * Create an instance of {@link SimpleLegend }
     * 
     */
    public SimpleLegend createSimpleLegend() {
        return new SimpleLegend();
    }

    /**
     * Create an instance of {@link LayerCollectionType }
     * 
     */
    public LayerCollectionType createLayerCollectionType() {
        return new LayerCollectionType();
    }

    /**
     * Create an instance of {@link IdTime }
     * 
     */
    public IdTime createIdTime() {
        return new IdTime();
    }

    /**
     * Create an instance of {@link Legends }
     * 
     */
    public Legends createLegends() {
        return new Legends();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LayerCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "org.orbisgis.mapContext", name = "layer-collection")
    public JAXBElement<LayerCollectionType> createLayerCollection(LayerCollectionType value) {
        return new JAXBElement<LayerCollectionType>(_LayerCollection_QNAME, LayerCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LayerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "org.orbisgis.mapContext", name = "layer")
    public JAXBElement<LayerType> createLayer(LayerType value) {
        return new JAXBElement<LayerType>(_Layer_QNAME, LayerType.class, null, value);
    }

}
