//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 12:40:38 PM CEST 
//


package net.opengis.wms._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import net.opengis.ows._2.CodeType;
import net.opengis.ows._2.DescriptionType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/ows/2.0}DescriptionType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/ows/2.0}Identifier"/>
 *         &lt;element ref="{http://www.opengis.net/wms/2.0}LegendURL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StyleSheetURL" type="{http://www.opengis.net/wms/2.0}FormattedOnlineResource" minOccurs="0"/>
 *         &lt;element name="StyleURL" type="{http://www.opengis.net/wms/2.0}FormattedOnlineResource" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identifier",
    "legendURL",
    "styleSheetURL",
    "styleURL"
})
@XmlRootElement(name = "Style")
public class Style
    extends DescriptionType
{

    @XmlElement(name = "Identifier", namespace = "http://www.opengis.net/ows/2.0", required = true)
    protected CodeType identifier;
    @XmlElement(name = "LegendURL")
    protected List<LegendURL> legendURL;
    @XmlElement(name = "StyleSheetURL")
    protected FormattedOnlineResource styleSheetURL;
    @XmlElement(name = "StyleURL")
    protected FormattedOnlineResource styleURL;
    @XmlAttribute
    protected Boolean isDefault;

    /**
     * An unambiguous reference to this style, identifying a specific version when needed, normally used by software
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setIdentifier(CodeType value) {
        this.identifier = value;
    }

    /**
     * Description of an image that represents the legend of the map Gets the value of the legendURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the legendURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLegendURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LegendURL }
     * 
     * 
     */
    public List<LegendURL> getLegendURL() {
        if (legendURL == null) {
            legendURL = new ArrayList<LegendURL>();
        }
        return this.legendURL;
    }

    /**
     * Gets the value of the styleSheetURL property.
     * 
     * @return
     *     possible object is
     *     {@link FormattedOnlineResource }
     *     
     */
    public FormattedOnlineResource getStyleSheetURL() {
        return styleSheetURL;
    }

    /**
     * Sets the value of the styleSheetURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormattedOnlineResource }
     *     
     */
    public void setStyleSheetURL(FormattedOnlineResource value) {
        this.styleSheetURL = value;
    }

    /**
     * Gets the value of the styleURL property.
     * 
     * @return
     *     possible object is
     *     {@link FormattedOnlineResource }
     *     
     */
    public FormattedOnlineResource getStyleURL() {
        return styleURL;
    }

    /**
     * Sets the value of the styleURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormattedOnlineResource }
     *     
     */
    public void setStyleURL(FormattedOnlineResource value) {
        this.styleURL = value;
    }

    /**
     * Gets the value of the isDefault property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDefault() {
        return isDefault;
    }

    /**
     * Sets the value of the isDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDefault(Boolean value) {
        this.isDefault = value;
    }

}
