/* Generated By:JJTree: Do not edit this line. ASTSQLCompareExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.gdms.sql.parser;

public
class ASTSQLCompareExpr extends SimpleNode {
  public ASTSQLCompareExpr(int id) {
    super(id);
  }

  public ASTSQLCompareExpr(SQLEngine p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLEngineVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bd8a8249f38e1f9725acd742726e69a0 (do not edit this line) */
