/* Generated By:JJTree: Do not edit this line. ASTSQLOrderBy.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.gdms.sql.parser;

public
class ASTSQLOrderBy extends SimpleNode {
  public ASTSQLOrderBy(int id) {
    super(id);
  }

  public ASTSQLOrderBy(SQLEngine p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLEngineVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b6f5245f50e51147a5acf68635d4b5f9 (do not edit this line) */
