/*
 * OrbisGIS is a GIS application dedicated to scientific spatial simulation.
 * This cross-platform GIS is developed at French IRSTV institute and is able
 * to manipulate and create vector and raster spatial information. OrbisGIS
 * is distributed under GPL 3 license. It is produced  by the geo-informatic team of
 * the IRSTV Institute <http://www.irstv.cnrs.fr/>, CNRS FR 2488:
 *    Erwan BOCHER, scientific researcher,
 *    Thomas LEDUC, scientific researcher,
 *    Fernando GONZALEZ CORTES, computer engineer.
 *
 * Copyright (C) 2007 Erwan BOCHER, Fernando GONZALEZ CORTES, Thomas LEDUC
 *
 * This file is part of OrbisGIS.
 *
 * OrbisGIS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OrbisGIS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OrbisGIS. If not, see <http://www.gnu.org/licenses/>.
 *
 * For more information, please consult:
 *    <http://orbisgis.cerma.archi.fr/>
 *    <http://sourcesup.cru.fr/projects/orbisgis/>
 *
 * or contact directly:
 *    erwan.bocher _at_ ec-nantes.fr
 *    fergonco _at_ gmail.com
 *    thomas.leduc _at_ cerma.archi.fr
 */
/*
 * VentanaFlowLayoutPreview.java
 *
 * Created on 1 de mayo de 2008, 8:50
 */

package org.orbisgis.editorViews.toc.actions.cui.gui.widgets;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.net.URL;
import java.util.ArrayList;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;

import org.gdms.data.types.GeometryConstraint;
import org.orbisgis.ExtendedWorkspace;
import org.orbisgis.Services;
import org.orbisgis.editorViews.toc.actions.cui.gui.LegendContext;
import org.orbisgis.editorViews.toc.actions.cui.persistence.Compositesymboltype;
import org.orbisgis.editorViews.toc.actions.cui.persistence.ObjectFactory;
import org.orbisgis.editorViews.toc.actions.cui.persistence.Simplesymboltype;
import org.orbisgis.editorViews.toc.actions.cui.persistence.Symbolcollection;
import org.orbisgis.editorViews.toc.actions.cui.ui.SymbolEditor;
import org.orbisgis.images.IconLoader;
import org.orbisgis.renderer.legend.LegendFactory;
import org.orbisgis.renderer.legend.UniqueSymbolLegend;
import org.orbisgis.renderer.symbol.CircleSymbol;
import org.orbisgis.renderer.symbol.EditableSymbol;
import org.orbisgis.renderer.symbol.LineSymbol;
import org.orbisgis.renderer.symbol.PolygonSymbol;
import org.orbisgis.renderer.symbol.Symbol;
import org.orbisgis.renderer.symbol.SymbolFactory;
import org.sif.UIFactory;
import org.sif.UIPanel;

/**
 *
 * @author david
 */
public class FlowLayoutPreviewWindow extends javax.swing.JPanel implements
		UIPanel {

	public static final String SYMBOL_COLLECTION_FILE = "org.orbisgis.symbol-collection.xml";
	private LegendContext legendContext;
	private ArrayList<SelectableCanvas> selection = new ArrayList<SelectableCanvas>();

	/** Creates new form VentanaFlowLayoutPreview */
	public FlowLayoutPreviewWindow(LegendContext legendContext) {
		this.legendContext = legendContext;
		initComponents();
		try {
			ExtendedWorkspace ew = (ExtendedWorkspace) Services
					.getService("org.orbisgis.ExtendedWorkspace");
			loadXML(new FileInputStream(ew.getFile(SYMBOL_COLLECTION_FILE)));
		} catch (FileNotFoundException e) {
			System.out.println("Collection not loaded: " + e.getMessage());
		} catch (JAXBException e) {
			System.out.println("Collection not loaded: " + e.getMessage());
		} catch (NullPointerException e) {
			System.out.println("Collection not loaded: " + e.getMessage());
		}
		// setAbstractActions();
		refreshInterface();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanelPreviewSymbols = new javax.swing.JPanel();
		jToolBar1 = new javax.swing.JToolBar();
		jButtonAdd = new javax.swing.JButton();
		jButtonEdit = new javax.swing.JButton();
		jButtonDel = new javax.swing.JButton();

		jPanelPreviewSymbols.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());
		jPanelPreviewSymbols.setLayout(new java.awt.FlowLayout(
				java.awt.FlowLayout.LEFT));

		jToolBar1.setFloatable(false);
		jToolBar1.setRollover(true);

		jButtonAdd.setIcon(IconLoader.getIcon("add.png"));
		jButtonAdd.setToolTipText("Add");
		jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonAddActionPerformed(evt);
			}
		});
		jToolBar1.add(jButtonAdd);

		jButtonEdit.setIcon(IconLoader.getIcon("pencil.png"));
		jButtonEdit.setToolTipText("Edit");
		jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonEditActionPerformed(evt);
			}
		});
		jToolBar1.add(jButtonEdit);

		jButtonDel.setIcon(IconLoader.getIcon("delete.png"));
		jButtonDel.setToolTipText("Delete");
		jButtonDel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonDelActionPerformed(evt);
			}
		});
		jToolBar1.add(jButtonDel);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jPanelPreviewSymbols,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																453,
																Short.MAX_VALUE)
														.addComponent(
																jToolBar1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																453,
																Short.MAX_VALUE))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jToolBar1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												25,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanelPreviewSymbols,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												367, Short.MAX_VALUE)
										.addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonDelActionPerformed
		Component[] comps = jPanelPreviewSymbols.getComponents();
		for (int i = 0; i < comps.length; i++) {
			if (comps[i] instanceof SelectableCanvas) {
				SelectableCanvas can = (SelectableCanvas) comps[i];

				if (selection.contains(can)) {
					selection.remove(can);
					jPanelPreviewSymbols.remove(can);
				}
			}
		}

		refreshInterface();

	}// GEN-LAST:event_jButtonDelActionPerformed

	private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {
		Component[] comps = jPanelPreviewSymbols.getComponents();
		for (int i = 0; i < comps.length; i++) {
			if (comps[i] instanceof SelectableCanvas) {
				SelectableCanvas can = (SelectableCanvas) comps[i];

				if (selection.contains(can)) {
					Symbol sym = can.getSymbol();
					UniqueSymbolLegend leg = LegendFactory
							.createUniqueSymbolLegend();
					leg.setSymbol(sym);
					SymbolEditor usl = new SymbolEditor(false, legendContext);

					if (UIFactory.showDialog(usl)) {
						can.setSymbol(usl.getSymbolComposite());
					}

				}

			}
		}
		refreshInterface();
	}

	private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAddActionPerformed

		// Symbol sym = SymbolFactory.createCirclePointSymbol(Color.BLACK,
		// Color.BLUE, 20);
		JPanelTypeOfGeometrySelection type = new JPanelTypeOfGeometrySelection(
				SymbolEditor.getAvailableSymbols());
		if (UIFactory.showDialog(type)) {
			EditableSymbol sym = (EditableSymbol) type.getSelected();

			SymbolEditor usl = new SymbolEditor(false, legendContext);
			usl.setSymbol(sym);

			if (UIFactory.showDialog(usl)) {
				addSymbolToPanel(usl.getSymbolComposite());

				refreshInterface();
			}

		}

	}// GEN-LAST:event_jButtonAddActionPerformed

	private void jPanelPreviewSymbolsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelPreviewSymbolsMouseClicked
		Component c = evt.getComponent();
		if (c instanceof SelectableCanvas) {
			SelectableCanvas can = (SelectableCanvas) c;
			if (evt.isControlDown()) {
				if (selection.contains(can)) {
					selection.remove(can);
					can.setSelected(false);
				} else {
					selection.add(can);
					can.setSelected(true);
				}
			} else {
				for (SelectableCanvas canvas : selection) {
					canvas.setSelected(false);
				}
				selection.clear();
				selection.add(can);
				can.setSelected(true);
			}

		}
		refreshInterface();

	}// GEN-LAST:event_jPanelPreviewSymbolsMouseClicked

	private void refreshInterface() {

		try {
			ExtendedWorkspace ew = (ExtendedWorkspace) Services
					.getService("org.orbisgis.ExtendedWorkspace");
			saveXML(new FileOutputStream(ew.getFile(SYMBOL_COLLECTION_FILE)));
		} catch (FileNotFoundException e) {
			System.out.println("Collection not saved: " + e.getMessage());
		} catch (JAXBException e) {
			System.out.println("Collection not saved: " + e.getMessage());
		} catch (NullPointerException e) {
			System.out.println("Collection not saved: " + e.getMessage());
		}

		Component[] comps = jPanelPreviewSymbols.getComponents();
		jButtonDel.setEnabled(false);
		jButtonEdit.setEnabled(false);
		for (int i = 0; i < comps.length; i++) {
			if (comps[i] instanceof SelectableCanvas) {
				SelectableCanvas can = (SelectableCanvas) comps[i];

				if (selection.contains(can)) {
					jButtonDel.setEnabled(true);
					if (!jButtonEdit.isEnabled()) {
						jButtonEdit.setEnabled(true);
					} else {
						jButtonEdit.setEnabled(false);
					}

				}
			}
		}

		jPanelPreviewSymbols.validate();
		jPanelPreviewSymbols.repaint();
	}

	/**
	 * Create a xml file in the specified path (file) with all the values of the
	 * collection
	 *
	 * @param file
	 * @throws JAXBException
	 */

	private void saveXML(FileOutputStream file) throws JAXBException {
		ObjectFactory of = new ObjectFactory();
		Symbolcollection coll = of.createSymbolcollection();

		ArrayList<Simplesymboltype> syms = (ArrayList<Simplesymboltype>) coll
				.getSimpleSymbol();
		ArrayList<Compositesymboltype> comp = (ArrayList<Compositesymboltype>) coll
				.getCompositeSymbol();

		Component[] comps = jPanelPreviewSymbols.getComponents();
		for (int i = 0; i < comps.length; i++) {
			if (comps[i] instanceof SelectableCanvas) {
				SelectableCanvas can = (SelectableCanvas) comps[i];

				Symbol sym = can.getSymbol();

				Simplesymboltype sst = createSimple(sym);
				syms.add(sst);

				Compositesymboltype cst = createComposite(sym);

				comp.add(cst);

			}
		}
		saveCollection(coll, file);
	}

	/**
	 * creates a simple symbol type object of JAXB
	 *
	 * @param sym
	 *            the simple symbol to serialize
	 * @param constraint
	 *            the type of the symbol
	 * @return Symplesymboltype
	 */
	public Simplesymboltype createSimple(Symbol sym) {
		ObjectFactory of = new ObjectFactory();

		Simplesymboltype sst = of.createSimplesymboltype();
		return sst;
	}

	/**
	 * creates a composite symbol of jaxb
	 *
	 * @param com
	 *            the symbol composite
	 * @return Compositesymboltype
	 */
	public Compositesymboltype createComposite(Symbol com) {
		ObjectFactory of = new ObjectFactory();

		Compositesymboltype cst = of.createCompositesymboltype();

		ArrayList<Simplesymboltype> simple = (ArrayList<Simplesymboltype>) cst
				.getSimpleSymbol();

		Simplesymboltype sst = of.createSimplesymboltype();

		for (int j = 0; j < com.getSymbolCount(); j++) {

			Symbol sim = com.getSymbol(j);

			sst = of.createSimplesymboltype();

			if (sim instanceof LineSymbol) {
				LineSymbol lineSim = (LineSymbol) sim;
				sst.setGeometryType(String
						.valueOf(GeometryConstraint.LINESTRING));

			}

			if (sim instanceof PolygonSymbol) {
				PolygonSymbol poliSim = (PolygonSymbol) sim;
				sst.setGeometryType(String.valueOf(GeometryConstraint.POLYGON));

			}

			if (sim instanceof CircleSymbol) {
				CircleSymbol circSim = (CircleSymbol) sim;
				sst.setGeometryType(String.valueOf(GeometryConstraint.POINT));

			}

			simple.add(sst);

		}

		return cst;
	}

	/**
	 * Saves the collection object in the specified file
	 *
	 * @param coll
	 * @param file
	 * @throws JAXBException
	 */
	public void saveCollection(Symbolcollection coll, FileOutputStream file)
			throws JAXBException {
		JAXBContext jaxbContext = JAXBContext.newInstance(
				"org.orbisgis.editorViews.toc.actions.cui.persistence", this
						.getClass().getClassLoader());
		// JAXBContext
		// jaxbContext=JAXBContext.newInstance("org.orbisgis.geoview.cui.gui.symbolcollection");
		Marshaller m = jaxbContext.createMarshaller();

		m.marshal(coll, file);
	}

	/**
	 * loads a collection object and returns it from the specified file
	 *
	 * @param file
	 * @return Symbolcollection
	 * @throws JAXBException
	 */
	public Symbolcollection loadCollection(FileInputStream file)
			throws JAXBException {
		JAXBContext jaxbContext = JAXBContext.newInstance(
				"org.orbisgis.editorViews.toc.actions.cui.persistence", this
						.getClass().getClassLoader());
		Unmarshaller u = jaxbContext.createUnmarshaller();

		Symbolcollection coll = (Symbolcollection) u.unmarshal(file);
		return coll;
	}

	/**
	 * loads an xml file and creates the panels for the created symbols
	 *
	 * @param fileInputStream
	 * @throws JAXBException
	 */
	private void loadXML(FileInputStream fileInputStream) throws JAXBException {
		// JAXBContext
		// jaxbContext=JAXBContext.newInstance("org.orbisgis.geoview.cui.gui.symbolcollection");
		Symbolcollection coll = loadCollection(fileInputStream);

		ArrayList<Simplesymboltype> sst = (ArrayList<Simplesymboltype>) coll
				.getSimpleSymbol();
		ArrayList<Compositesymboltype> cst = (ArrayList<Compositesymboltype>) coll
				.getCompositeSymbol();

		for (int i = 0; i < sst.size(); i++) {
			Simplesymboltype sim = sst.get(i);

			int constraint = Integer.parseInt(sim.getGeometryType());
			int out;
			int fill;
			Color outlineColor;
			Color fillColor;
			String outlineSize;

			switch (constraint) {
			case GeometryConstraint.POLYGON:
				outlineSize = sim.getOutlineSize();
				if (outlineSize == null) {
					outlineSize = "1.0";
				}
				out = Integer.parseInt(sim.getLineColor());
				fill = Integer.parseInt(sim.getFillColor());
				if (sim.getLineColor() != null)
					outlineColor = new Color(out);
				else
					outlineColor = Color.white;

				if (sim.getFillColor() != null)
					fillColor = new Color(fill);
				else
					fillColor = Color.white;

				PolygonSymbol pol = (PolygonSymbol) SymbolFactory
						.createPolygonSymbol(outlineColor, Integer
								.parseInt(outlineSize), fillColor);
				addSymbolToPanel(pol);
				break;
			case GeometryConstraint.POINT:
				out = Integer.parseInt(sim.getLineColor());
				fill = Integer.parseInt(sim.getFillColor());

				if (sim.getLineColor() != null)
					outlineColor = new Color(out);
				else
					outlineColor = Color.white;

				if (sim.getFillColor() != null)
					fillColor = new Color(fill);
				else
					fillColor = Color.white;

				String simbolSize = sim.getSimbolSize();
				if (simbolSize == null)
					simbolSize = "10";
				CircleSymbol cir = (CircleSymbol) SymbolFactory
						.createCirclePointSymbol(outlineColor, fillColor,
								Integer.parseInt(simbolSize));
				addSymbolToPanel(cir);
				break;
			case GeometryConstraint.LINESTRING:
				outlineSize = sim.getOutlineSize();
				if (outlineSize == null)
					outlineSize = "1.0";
				out = Integer.parseInt(sim.getLineColor());
				if (sim.getLineColor() != null)
					outlineColor = new Color(out);
				else
					outlineColor = Color.white;

				LineSymbol lin = (LineSymbol) SymbolFactory.createLineSymbol(
						outlineColor, Integer.parseInt(outlineSize));
				addSymbolToPanel(lin);
				break;

			}
		}

		for (int i = 0; i < cst.size(); i++) {
			Compositesymboltype comp = cst.get(i);
			ArrayList<Simplesymboltype> simp = (ArrayList<Simplesymboltype>) comp
					.getSimpleSymbol();

			Symbol[] simbolComp = new Symbol[simp.size()];

			for (int j = 0; j < simp.size(); j++) {
				Simplesymboltype sym = simp.get(j);

				int constraint = Integer.parseInt(sym.getGeometryType());
				int out;
				int fill;
				Color outlineColor;
				Color fillColor;
				String outlineSize;

				switch (constraint) {
				case GeometryConstraint.POLYGON:
					outlineSize = sym.getOutlineSize();
					if (outlineSize == null) {
						outlineSize = "1.0";
					}
					out = Integer.parseInt(sym.getLineColor());
					fill = Integer.parseInt(sym.getFillColor());
					if (sym.getLineColor() != null)
						outlineColor = new Color(out);
					else
						outlineColor = Color.white;

					if (sym.getFillColor() != null)
						fillColor = new Color(fill);
					else
						fillColor = Color.white;

					PolygonSymbol pol = (PolygonSymbol) SymbolFactory
							.createPolygonSymbol(outlineColor, Integer
									.parseInt(outlineSize), fillColor);

					simbolComp[j] = pol;
					break;
				case GeometryConstraint.POINT:
					out = Integer.parseInt(sym.getLineColor());
					fill = Integer.parseInt(sym.getFillColor());

					if (sym.getLineColor() != null)
						outlineColor = new Color(out);
					else
						outlineColor = Color.white;

					if (sym.getFillColor() != null)
						fillColor = new Color(fill);
					else
						fillColor = Color.white;

					String simbolSize = sym.getSimbolSize();
					if (simbolSize == null)
						simbolSize = "10";
					CircleSymbol cir = (CircleSymbol) SymbolFactory
							.createCirclePointSymbol(outlineColor, fillColor,
									Integer.parseInt(simbolSize));
					simbolComp[j] = cir;
					break;
				case GeometryConstraint.LINESTRING:
					outlineSize = sym.getOutlineSize();
					if (outlineSize == null)
						outlineSize = "1.0";
					out = Integer.parseInt(sym.getLineColor());
					if (sym.getLineColor() != null)
						outlineColor = new Color(out);
					else
						outlineColor = Color.white;
					//
					LineSymbol lin = (LineSymbol) SymbolFactory
							.createLineSymbol(outlineColor, Integer
									.parseInt(outlineSize));
					simbolComp[j] = lin;
					break;

				}

			}
			Symbol compositeSymbol = SymbolFactory
					.createSymbolComposite(simbolComp);
			addSymbolToPanel(compositeSymbol);

		}

	}

	private void addSymbolToPanel(Symbol sym) {
		SelectableCanvas can = new SelectableCanvas();

		can.setSymbol(sym);
		can.setPreferredSize(new Dimension(126, 70));

		can.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jPanelPreviewSymbolsMouseClicked(evt);
			}
		});

		jPanelPreviewSymbols.add(can);
	}

	public Symbol getSelectedSymbol() {
		return selection.get(0).getSymbol();
	}

	private SelectableCanvas getSelectedCanvas() {
		Component[] comps = jPanelPreviewSymbols.getComponents();
		for (int i = 0; i < comps.length; i++) {
			if (comps[i] instanceof SelectableCanvas) {
				SelectableCanvas can = (SelectableCanvas) comps[i];

				if (selection.contains(can)) {
					return can;
				}
			}
		}
		return null;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonAdd;
	private javax.swing.JButton jButtonDel;
	private javax.swing.JButton jButtonEdit;
	private javax.swing.JPanel jPanelPreviewSymbols;
	private javax.swing.JToolBar jToolBar1;

	// End of variables declaration//GEN-END:variables

	public Component getComponent() {
		return this;
	}

	public URL getIconURL() {
		return null;
	}

	public String getInfoText() {
		return "Select a symbol to add it to the collection";
	}

	public String getTitle() {
		return "Symbol collection";
	}

	public String initialize() {
		return null;
	}

	public String postProcess() {

		return null;
	}

	public String validateInput() {
		if (selection.size() == 0) {
			return "A symbol must be selected";
		} else if (selection.size() > 1) {
			return "Only one symbol should be selected";
		} else {
			Symbol symbol = getSelectedCanvas().getSymbol();
			String ret = acceptsGeometry(symbol);
			if (ret != null) {
				return ret;
			}
		}

		return null;
	}

	private String acceptsGeometry(Symbol symbol) {
		if (symbol instanceof EditableSymbol) {
			if (!((EditableSymbol) symbol).acceptGeometryType(legendContext
					.getGeometryConstraint())) {
				return "The symbol type is not applicable";
			} else {
				return null;
			}
		} else if (symbol.acceptsChildren()) {
			for (int i = 0; i < symbol.getSymbolCount(); i++) {
				String ret = acceptsGeometry(symbol.getSymbol(i));
				if (ret != null) {
					return ret;
				}
			}
		}

		return null;
	}

}
