#!/usr/bin/env bash
#
# Utility to add javadoc links to the online (GitHub) source
# Must be run from the root of the git repository, after generating the javadoc for any/all the modules

# parameter, if exist, is the revision to display (git revision or branche name)
# defaults to master
if [ $# -eq 0 ]
then
  rev="master"
else
  rev="$1"
fi

dirs="gdms orbisgis-core orbisgis-ui"

for d in $dirs
do
	url=$(echo "https://github.com/irstv/orbisgis/tree/${rev}/${d}/src/main/java" | sed 's/\//\\\//g')

	rm -rf "${d}/target/site/apidocs/src-html"
	files=$(find ${d}/target/site/apidocs/ -name "*.html" -type f)

	sed -i "s/\(\\.\\.\/\)\+src-html\(.*\).html#line\.\([0-9]\+\)\">/${url}\2.java#L\3\" target=\"_blank\"/g" ${files}
done